stages:
  - print_env
  - build_and_push
  - deploy

variables:
  # Using GRADLE_PROFILE instead of MVN_PROFILE for clarity.
  # Setting 'dev' as the default for the dev branch.
  GRADLE_PROFILE: "dev"
  CONTAINER_NM: "back-demo-project"
  INST_TAG_KEY: "appType"
  INST_TAG_VAL: "docker-dev-deploy" # Assuming dev values for dev branch

print_env:
  stage: print_env
  script:
    - printenv
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"

build_and_push:
  stage: build_and_push
  image: docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo "Building with profile: $GRADLE_PROFILE"
    - docker build --build-arg PROFILE=$GRADLE_PROFILE -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE:$GRADLE_PROFILE-latest"
    - docker push "$CI_REGISTRY_IMAGE:$GRADLE_PROFILE-latest"
    - docker logout
    - docker rmi -f "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker rmi -f "$CI_REGISTRY_IMAGE:$GRADLE_PROFILE-latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli:2.15.50
    entrypoint: [""]
  script:
    - aws --version
    - |
      aws ssm send-command \
          --targets "Key=tag:${INST_TAG_KEY},Values=${INST_TAG_VAL}" \
          --document-name "AWS-RunShellScript" \
          --parameters "{\"commands\":[\"sudo su - ec2-user -c 'docker login -u ${CUSTOM_REGISTRY_USER} -p ${CUSTOM_REGISTRY_TOKEN} ${CI_REGISTRY} && \
            docker-compose pull ${CONTAINER_NM} && \
            docker-compose up -d ${CONTAINER_NM} && \
            docker logout'\"]}"
  variables:
    AWS_ACCESS_KEY_ID: $AWS_GITLAB_CICD_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY: $AWS_GITLAB_CICD_SECRET_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"