spring.application.name=back-demo-project

# H2 Database
spring.datasource.url=jdbc:h2:mem:surveydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ?? ??? ??
# ? data.sql? ?? ??
spring.sql.init.mode=always
# ? JPA ??? ?? ?? data.sql ??
spring.jpa.defer-datasource-initialization=true

# Swagger UI Schemas ???
springdoc.swagger-ui.default-models-expand-depth=-1